export interface Option {
  value: string | number;
  label: string;
  children?: Option[];
  isActive: boolean;
  type: string;
  id: number;
}

export const governmentData: Option[] = [
  {
    label: 'Parastatal 1',
    type: 'parastatal',
    isActive: false,
    value: 'parastatal1',
    children: [
      {
        id: 1,
        label: 'Office 1',
        type: 'office',
        isActive: false,
        value: 'office1',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 2,
        label: 'Office 2',
        type: 'office',
        isActive: false,
        value: 'office2',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 3,
        label: 'Office 3',
        isActive: false,
        type: 'office',
        value: 'office3',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 4,
        label: 'Office 4',
        isActive: false,
        type: 'office',
        value: 'office4',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 5,
        label: 'Office 5',
        type: 'office',
        isActive: false,
        value: 'office5',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 6,
        label: 'Office 6',
        isActive: false,
        type: 'office',
        value: 'office6',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 7,
        label: 'Office 7',
        isActive: false,
        type: 'office',
        value: 'office7',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
    ],
    id: 1,
  },
  {
    label: 'Parastatal 2',
    type: 'parastatal',
    isActive: false,
    value: 'parastatal2',
    children: [
      {
        id: 1,
        label: 'Office 1',
        type: 'office',
        isActive: false,
        value: 'office1',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 2,
        label: 'Office 2',
        type: 'office',
        isActive: false,
        value: 'office2',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 3,
        label: 'Office 3',
        isActive: false,
        type: 'office',
        value: 'office3',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 4,
        label: 'Office 4',
        isActive: false,
        type: 'office',
        value: 'office4',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 5,
        label: 'Office 5',
        type: 'office',
        isActive: false,
        value: 'office5',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 6,
        label: 'Office 6',
        isActive: false,
        type: 'office',
        value: 'office6',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 7,
        label: 'Office 7',
        isActive: false,
        type: 'office',
        value: 'office7',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
    ],
    id: 2,
  },
  {
    label: 'Parastatal 3',
    type: 'parastatal',
    isActive: false,
    value: 'parastatal3',
    children: [
      {
        id: 1,
        label: 'Office 1',
        type: 'office',
        isActive: false,
        value: 'office1',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 2,
        label: 'Office 2',
        type: 'office',
        isActive: false,
        value: 'office2',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 3,
        label: 'Office 3',
        isActive: false,
        type: 'office',
        value: 'office3',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 4,
        label: 'Office 4',
        isActive: false,
        type: 'office',
        value: 'office4',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 5,
        label: 'Office 5',
        type: 'office',
        isActive: false,
        value: 'office5',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 6,
        label: 'Office 6',
        isActive: false,
        type: 'office',
        value: 'office6',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 7,
        label: 'Office 7',
        isActive: false,
        type: 'office',
        value: 'office7',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
    ],
    id: 3,
  },
  {
    label: 'Parastatal 4',
    type: 'parastatal',
    isActive: false,
    value: 'parastatal4',
    children: [
      {
        id: 1,
        label: 'Office 1',
        type: 'office',
        isActive: false,
        value: 'office1',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 2,
        label: 'Office 2',
        type: 'office',
        isActive: false,
        value: 'office2',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 3,
        label: 'Office 3',
        isActive: false,
        type: 'office',
        value: 'office3',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 4,
        label: 'Office 4',
        isActive: false,
        type: 'office',
        value: 'office4',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 5,
        label: 'Office 5',
        type: 'office',
        isActive: false,
        value: 'office5',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 6,
        label: 'Office 6',
        isActive: false,
        type: 'office',
        value: 'office6',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
      {
        id: 7,
        label: 'Office 7',
        isActive: false,
        type: 'office',
        value: 'office7',
        children: [
          {
            id: 1,
            label: 'Department 1',
            type: 'department',
            value: 'department1',
            isActive: false,
          },
          {
            id: 2,
            label: 'Department 2',
            type: 'department',
            value: 'department2',
            isActive: false,
          },
          {
            id: 3,
            label: 'Department 3',
            type: 'department',
            value: 'department3',
            isActive: false,
          },
          {
            id: 4,
            label: 'Department 4',
            type: 'department',
            value: 'department4',
            isActive: false,
          },
          {
            id: 5,
            label: 'Department 5',
            type: 'department',
            value: 'department5',
            isActive: false,
          },
          {
            id: 6,
            label: 'Department 6',
            type: 'department',
            value: 'department6',
            isActive: false,
          },
          {
            id: 7,
            label: 'Department 7',
            type: 'department',
            value: 'department7',
            isActive: false,
          },
        ],
      },
    ],
    id: 4,
  },
];

// export const governmentData = [
//   {
//     value: 'Parastatal 1',
//     type: 'parastatal',
//     isActive: false,
//     key: 'parastatal1',
//     children: [
//       {
//         id: 1,
//         value: 'Office 1',
//         type: 'office',
//         isActive: false,
//         key: 'office1',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 2,
//         value: 'Office 2',
//         type: 'office',
//         isActive: false,
//         key: 'office2',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 3,
//         value: 'Office 3',
//         isActive: false,
//         type: 'office',
//         key: 'office3',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 4,
//         value: 'Office 4',
//         isActive: false,
//         type: 'office',
//         key: 'office4',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 5,
//         value: 'Office 5',
//         type: 'office',
//         isActive: false,
//         key: 'office5',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 6,
//         value: 'Office 6',
//         isActive: false,
//         type: 'office',
//         key: 'office6',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 7,
//         value: 'Office 7',
//         isActive: false,
//         type: 'office',
//         key: 'office7',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//     ],
//     id: 1,
//   },
//   {
//     value: 'Parastatal 2',
//     type: 'parastatal',
//     isActive: false,
//     key: 'parastatal2',
//     children: [
//       {
//         id: 1,
//         value: 'Office 1',
//         type: 'office',
//         isActive: false,
//         key: 'office1',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 2,
//         value: 'Office 2',
//         type: 'office',
//         isActive: false,
//         key: 'office2',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 3,
//         value: 'Office 3',
//         isActive: false,
//         type: 'office',
//         key: 'office3',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 4,
//         value: 'Office 4',
//         isActive: false,
//         type: 'office',
//         key: 'office4',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 5,
//         value: 'Office 5',
//         type: 'office',
//         isActive: false,
//         key: 'office5',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 6,
//         value: 'Office 6',
//         isActive: false,
//         type: 'office',
//         key: 'office6',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 7,
//         value: 'Office 7',
//         isActive: false,
//         type: 'office',
//         key: 'office7',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//     ],
//     id: 2,
//   },
//   {
//     value: 'Parastatal 3',
//     type: 'parastatal',
//     isActive: false,
//     key: 'parastatal3',
//     children: [
//       {
//         id: 1,
//         value: 'Office 1',
//         type: 'office',
//         isActive: false,
//         key: 'office1',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 2,
//         value: 'Office 2',
//         type: 'office',
//         isActive: false,
//         key: 'office2',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 3,
//         value: 'Office 3',
//         isActive: false,
//         type: 'office',
//         key: 'office3',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 4,
//         value: 'Office 4',
//         isActive: false,
//         type: 'office',
//         key: 'office4',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 5,
//         value: 'Office 5',
//         type: 'office',
//         isActive: false,
//         key: 'office5',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 6,
//         value: 'Office 6',
//         isActive: false,
//         type: 'office',
//         key: 'office6',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 7,
//         value: 'Office 7',
//         isActive: false,
//         type: 'office',
//         key: 'office7',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//     ],
//     id: 3,
//   },
//   {
//     value: 'Parastatal 4',
//     type: 'parastatal',
//     isActive: false,
//     key: 'parastatal4',
//     children: [
//       {
//         id: 1,
//         value: 'Office 1',
//         type: 'office',
//         isActive: false,
//         key: 'office1',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 2,
//         value: 'Office 2',
//         type: 'office',
//         isActive: false,
//         key: 'office2',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 3,
//         value: 'Office 3',
//         isActive: false,
//         type: 'office',
//         key: 'office3',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 4,
//         value: 'Office 4',
//         isActive: false,
//         type: 'office',
//         key: 'office4',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 5,
//         value: 'Office 5',
//         type: 'office',
//         isActive: false,
//         key: 'office5',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 6,
//         value: 'Office 6',
//         isActive: false,
//         type: 'office',
//         key: 'office6',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//       {
//         id: 7,
//         value: 'Office 7',
//         isActive: false,
//         type: 'office',
//         key: 'office7',
//         children: [
//           { value: 'Department 1', isActive: false, id: 1, type: 'department' },
//           { value: 'Department 2', isActive: false, id: 2, type: 'department' },
//           { value: 'Department 3', isActive: false, id: 3, type: 'department' },
//           { value: 'Department 4', isActive: false, id: 4, type: 'department' },
//           { value: 'Department 5', isActive: false, id: 5, type: 'department' },
//           { value: 'Department 6', isActive: false, id: 6, type: 'department' },
//           { value: 'Department 7', isActive: false, id: 7, type: 'department' },
//         ],
//       },
//     ],
//     id: 4,
//   },
// ];
