const genericDepartments = [
  {
    id: 1,
    key: 'department1',
    value: 'Department 1',
    isActive: false,
    type: 'department',
  },
  {
    id: 2,
    key: 'department2',
    value: 'Department 2',
    isActive: false,
    type: 'department',
  },
  {
    id: 3,
    key: 'department3',
    value: 'Department 3',
    isActive: false,
    type: 'department',
  },
  {
    id: 4,
    key: 'department4',
    value: 'Department 4',
    isActive: false,
    type: 'department',
  },
  {
    id: 5,
    key: 'department5',
    value: 'Department 5',
    isActive: false,
    type: 'department',
  },
  {
    id: 6,
    key: 'department6',
    value: 'Department 6',
    isActive: false,
    type: 'department',
  },
  {
    id: 7,
    key: 'department7',
    value: 'Department 7',
    isActive: false,
    type: 'department',
  },
];
const genericOffice = [
  {
    id: 1,
    value: 'Office 1',
    type: 'office',
    isActive: false,
    key: 'office1',
    children: genericDepartments,
  },
  {
    id: 2,
    value: 'Office 2',
    type: 'office',
    isActive: false,
    key: 'office2',
    children: genericDepartments,
  },
  {
    id: 3,
    value: 'Office 3',
    isActive: false,
    type: 'office',
    key: 'office3',
    children: genericDepartments,
  },
  {
    id: 4,
    value: 'Office 4',
    isActive: false,
    type: 'office',
    key: 'office4',
    children: genericDepartments,
  },
  {
    id: 5,
    value: 'Office 5',
    type: 'office',
    isActive: false,
    key: 'office5',
    children: genericDepartments,
  },
  {
    id: 6,
    value: 'Office 6',
    isActive: false,
    type: 'office',
    key: 'office6',
    children: genericDepartments,
  },
  {
    id: 7,
    value: 'Office 7',
    isActive: false,
    type: 'office',
    key: 'office7',
    children: genericDepartments,
  },
];

const newDepartment = [
  {
    id: 1,
    key: 'department1',
    value: 'All',
    isActive: false,
    type: 'department',
  },
  {
    id: 2,
    key: 'department2',
    value: 'Public relations',
    isActive: false,
    type: 'department',
  },
  {
    id: 3,
    key: 'department3',
    value: 'Human resources',
    isActive: false,
    type: 'department',
  },
];
const ITI = [
  {
    id: 1,
    value: 'All',
    type: 'office',
    isActive: false,
    key: 'office1',
    children: newDepartment,
  },
  {
    id: 2,
    value: 'Registry',
    type: 'office',
    isActive: false,
    key: 'office2',
    children: newDepartment,
  },
  {
    id: 3,
    value: 'Office of the Minister',
    isActive: false,
    type: 'office',
    key: 'office3',
    children: newDepartment,
  },
  {
    id: 4,
    value: 'Office of the Permanent Secretary',
    isActive: false,
    type: 'office',
    key: 'office4',
    children: newDepartment,
  },
  {
    id: 5,
    value: 'Finance and Budgets',
    type: 'office',
    isActive: false,
    key: 'office5',
    children: newDepartment,
  },
  {
    id: 6,
    value: 'Planning & Projects',
    isActive: false,
    type: 'office',
    key: 'office6',
    children: newDepartment,
  },
  {
    id: 7,
    value: 'Public Relations',
    isActive: false,
    type: 'office',
    key: 'office7',
    children: newDepartment,
  },
  {
    id: 8,
    value: 'Information Technology',
    isActive: false,
    type: 'office',
    key: 'office8',
    children: newDepartment,
  },
  {
    id: 9,
    value: 'Communications',
    isActive: false,
    type: 'office',
    key: 'office9',
    children: newDepartment,
  },
  {
    id: 10,
    value: 'Operations',
    isActive: false,
    type: 'office',
    key: 'office10',
    children: newDepartment,
  },
]

export const governmentData = [
  {
    value: 'Federal Ministry of Agriculture and Natural Resources ',
    type: 'parastatal',
    isActive: false,
    key: 'parastatal1',
    children: genericOffice,
    id: 1,
  },
  {
    value: 'Federal Ministry of Aviation',
    type: 'parastatal',
    isActive: false,
    key: 'parastatal2',
    children: genericOffice,
    id: 2,
  },
  {
    value: 'Federal Ministry of Industry, Trade and Investment',
    type: 'parastatal',
    isActive: false,
    key: 'parastatal3',
    children: ITI,
    id: 3,
  },
  {
    value: 'Federal Ministry of Commerce and Tourism',
    type: 'parastatal',
    isActive: false,
    key: 'parastatal4',
    children: genericOffice,
    id: 4,
  },
  {
    value: 'Federal Ministry of Communication',
    type: 'parastatal',
    isActive: false,
    key: 'parastatal4',
    children: genericOffice,
    id: 4,
  },
  {
    value: 'Federal Ministry of Petroleum Resources',
    type: 'parastatal',
    isActive: false,
    key: 'parastatal4',
    children: genericOffice,
    id: 4,
  },
  {
    value: 'Federal Ministry of Information and Culture ',
    type: 'parastatal',
    isActive: false,
    key: 'parastatal4',
    children: genericOffice,
    id: 4,
  },
  {
    value: 'Federal Ministry of Trasportation ',
    type: 'parastatal',
    isActive: false,
    key: 'parastatal4',
    children: genericOffice,
    id: 4,
  },
  {
    value: 'Federal Ministry of Foreign Affairs ',
    type: 'parastatal',
    isActive: false,
    key: 'parastatal4',
    children: genericOffice,
    id: 4,
  },
  {
    value: 'Federal Ministry of Health ',
    type: 'parastatal',
    isActive: false,
    key: 'parastatal4',
    children: genericOffice,
    id: 4,
  },
  {
    value: 'Federal Ministry of Education ',
    type: 'parastatal',
    isActive: false,
    key: 'parastatal4',
    children: genericOffice,
    id: 4,
  },
];
